### ISSUE TITLE
Initial ToDo List

### ISSUE THREAD

**Issue by ofa1** [MHMIC/wp-podcast-publisher#1]
- [ ] Push code
- [ ] Add credentials template
- [ ] Add config file 
- [ ] Make it installable
- [ ] Enrich MP3 tags

**Comment by omarmosid** [comment]
Suggest we make the fourth item its own issue and close this
